@echo off
echo ========================================
echo   Company Finder - API Key Setup
echo ========================================
echo.
echo This script will help you set up your API keys.
echo.

REM Check if config.py exists
if exist "config.py" (
    echo WARNING: config.py already exists!
    echo.
    choice /C YN /M "Do you want to overwrite it"
    if errorlevel 2 goto skip_config
)

echo.
echo ========================================
echo   Step 1: Google Places API Key
echo ========================================
echo.
echo To get your Google Places API key:
echo 1. Go to https://console.cloud.google.com/
echo 2. Create a project (or select existing)
echo 3. Enable "Places API"
echo 4. Create credentials - API Key
echo 5. Copy your API key
echo.
set /p GOOGLE_KEY="Enter your Google Places API Key: "

if "%GOOGLE_KEY%"=="" (
    echo ERROR: Google API key is required!
    pause
    exit /b 1
)

echo.
echo ========================================
echo   Step 2: Yelp API Key (Optional)
echo ========================================
echo.
echo To get your Yelp API key:
echo 1. Go to https://www.yelp.com/developers
echo 2. Create an app
echo 3. Copy your API key
echo.
set /p YELP_KEY="Enter your Yelp API Key (or press Enter to skip): "

echo.
echo ========================================
echo   Creating config.py file...
echo ========================================
echo.

(
echo # Configuration File
echo # Generated by setup_api_keys.bat
echo.
echo # Google Places API Key
echo GOOGLE_PLACES_API_KEY = '%GOOGLE_KEY%'
echo.
if not "%YELP_KEY%"=="" (
    echo # Yelp API Key
    echo YELP_API_KEY = '%YELP_KEY%'
) else (
    echo # Yelp API Key ^(not set^)
    echo YELP_API_KEY = ''
)
) > config.py

echo Config file created successfully!
echo.

:skip_config
echo ========================================
echo   Setting Environment Variables
echo ========================================
echo.
echo Setting temporary environment variables for this session...
set GOOGLE_PLACES_API_KEY=%GOOGLE_KEY%
if not "%YELP_KEY%"=="" set YELP_API_KEY=%YELP_KEY%

echo.
echo ========================================
echo   Setup Complete!
echo ========================================
echo.
echo Your API keys are now configured in:
echo   - config.py (permanent)
echo   - Environment variables (this session only)
echo.
echo To make environment variables permanent:
echo 1. Press Windows + R
echo 2. Type: sysdm.cpl
echo 3. Click "Environment Variables"
echo 4. Add GOOGLE_PLACES_API_KEY and YELP_API_KEY
echo.
echo Press any key to continue...
pause >nul

echo.
echo Starting the application...
echo.
python app.py

